const express = require("express");
const { Pool, types } = require("pg");
require("dotenv").config();

const ASAAS_API_KEY = process.env.ASAAS_API_KEY;
const ASAAS_BASE_URL = process.env.ASAAS_BASE_URL;
const ASAAS_WEBHOOK_TOKEN = process.env.ASAAS_WEBHOOK_TOKEN;

async function asaasRequest(endpoint, options = {}) {
    const resposta = await fetch(`${ASAAS_BASE_URL}${endpoint}`, {
        ...options,
        headers: {
            "Content-Type": "application/json",
            "access_token": ASAAS_API_KEY,
            ...(options.headers || {})
        }
    });

    const texto = await resposta.text();

    let dados;

    try {
        dados = JSON.parse(texto);
    } catch {
        dados = { resposta: texto };
    }

    if (!resposta.ok) {
        throw new Error(`Asaas ${resposta.status}: ${JSON.stringify(dados)}`);
    }

    return dados;
}

function dataHojeSaoPaulo() {
    return new Intl.DateTimeFormat("en-CA", {
        timeZone: "America/Sao_Paulo",
        year: "numeric",
        month: "2-digit",
        day: "2-digit"
    }).format(new Date());
}

function limparDocumento(valor) {
    return String(valor || "").replace(/\D/g, "");
}

const pool = new Pool({
    connectionString: process.env.DATABASE_URL,
    ssl: { rejectUnauthorized: false },
    max: 5
});

// Faz o PostgreSQL devolver NUMERIC como número JavaScript.
types.setTypeParser(1700, value => Number(value));

function converterPlaceholders(sql) {
    let indice = 0;
    return sql.replace(/\?/g, () => `$${++indice}`);
}

class DatabaseAdapter {
    prepare(sql) {
        const consulta = converterPlaceholders(sql);

        return {
            get: async (...params) => {
                const resultado = await pool.query(consulta, params);
                return resultado.rows[0];
            },
            all: async (...params) => {
                const resultado = await pool.query(consulta, params);
                return resultado.rows;
            },
            run: async (...params) => {
                let sqlFinal = consulta;

                // O SQLite usava lastInsertRowid. No PostgreSQL usamos RETURNING id.
                if (/^\s*INSERT\s+INTO/i.test(sqlFinal) && !/\bRETURNING\b/i.test(sqlFinal)) {
                    sqlFinal += " RETURNING id";
                }

                try {
                    const resultado = await pool.query(sqlFinal, params);
                    return {
                        changes: resultado.rowCount,
                        lastInsertRowid: resultado.rows[0]?.id
                    };
                } catch (erro) {
                    if (erro.code === "23505") {
                        erro.message = `UNIQUE constraint failed: ${erro.detail || erro.message}`;
                    }
                    throw erro;
                }
            }
        };
    }

    async exec(sql) {
        return pool.query(sql);
    }
}

const db = new DatabaseAdapter();

const app = express();
const PORT = process.env.PORT || 3000;

app.use(express.json());
app.use(express.static("public"));

async function inicializarBanco() {
    await db.exec(`
        CREATE TABLE IF NOT EXISTS reservas (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            data TEXT NOT NULL,
            horario TEXT NOT NULL,
            nome TEXT NOT NULL,
            cpf TEXT,
            whatsapp TEXT NOT NULL,
            escalda_pes INTEGER NOT NULL DEFAULT 0,
            total NUMERIC NOT NULL,
            reserva NUMERIC NOT NULL DEFAULT 50,
            restante NUMERIC NOT NULL,
            status TEXT NOT NULL DEFAULT 'confirmada',
            criado_em TEXT NOT NULL,
            asaas_payment_id TEXT
        );

        CREATE TABLE IF NOT EXISTS reservas_temporarias (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            data TEXT NOT NULL,
            horario TEXT NOT NULL,
            nome TEXT NOT NULL,
            cpf TEXT,
            whatsapp TEXT,
            escalda_pes INTEGER NOT NULL DEFAULT 0,
            total NUMERIC,
            asaas_customer_id TEXT,
            asaas_payment_id TEXT,
            pix_payload TEXT,
            pix_encoded_image TEXT,
            pix_expiration TEXT,
            expira_em BIGINT NOT NULL,
            criado_em TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS horarios_bloqueados (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            data TEXT NOT NULL,
            horario TEXT NOT NULL,
            criado_em TEXT NOT NULL,
            UNIQUE(data, horario)
        );

        CREATE TABLE IF NOT EXISTS asaas_eventos (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            asaas_event_id TEXT UNIQUE NOT NULL,
            evento TEXT NOT NULL,
            recebido_em TEXT NOT NULL
        );
    `);
}

/*
 * HORÃRIOS PADRÃƒO
 */

const schedule = [
    "09:00",
    "10:00",
    "11:00",
    "12:00",
    "14:00",
    "15:00",
    "16:00",
    "17:00",
    "18:00",
    "19:00",
    "20:00"
];


/*
 * LIMPA RESERVAS TEMPORÃRIAS EXPIRADAS
 */

async function limparReservasTemporarias() {

    await db.prepare(`
        DELETE FROM reservas_temporarias
        WHERE expira_em <= ?
    `).run(Date.now());

}


/*
 * TESTE
 */

app.get("/health", (req, res) => {

    res.json({
        status: "ok",
        sistema: "OxumarÃ© Massagem",
        banco: "PostgreSQL (Supabase)"
    });

});


/*
 * HORÃRIOS DISPONÃVEIS
 */

app.get("/api/horarios", async (req, res) => {

    const { data } = req.query;

    if (!data) {
        return res.status(400).json({
            erro: "Informe a data."
        });
    }

    await limparReservasTemporarias();

    const agora = new Date();
    const horariosDisponiveis = [];

    for (const horario of schedule) {
        const dataHorario = new Date(`${data}T${horario}:00`);

        if (dataHorario.getTime() < agora.getTime() + (60 * 60 * 1000)) {
            continue;
        }

        const temporaria = await db.prepare(`
            SELECT id
            FROM reservas_temporarias
            WHERE data = ?
              AND horario = ?
              AND expira_em > ?
            LIMIT 1
        `).get(data, horario, Date.now());

        if (temporaria) continue;

        const confirmada = await db.prepare(`
            SELECT id
            FROM reservas
            WHERE data = ?
              AND horario = ?
              AND status = 'confirmada'
            LIMIT 1
        `).get(data, horario);

        if (confirmada) continue;

        const bloqueado = await db.prepare(`
            SELECT id
            FROM horarios_bloqueados
            WHERE data = ?
              AND horario = ?
            LIMIT 1
        `).get(data, horario);

        if (bloqueado) continue;

        horariosDisponiveis.push(horario);
    }

    res.json({
        data,
        horarios: horariosDisponiveis
    });
});

/*
 * RESERVA TEMPORÃRIA
 */

app.post("/api/reservar-temporariamente", async (req, res) => {

   const {
    data,
    horario,
    nome,
    cpf,
    whatsapp,
    escaldaPes
} = req.body;


    if (
    !data ||
    !horario ||
    !nome ||
    !cpf ||
    !whatsapp
) {

        return res.status(400).json({
            erro: "Nome, cpf, WhatsApp, data e horÃ¡rio sÃ£o obrigatÃ³rios."
        });

    }


    await limparReservasTemporarias();


    /*
     * Verifica reserva confirmada
     */

    const confirmada = await db.prepare(`
        SELECT id
        FROM reservas
        WHERE data = ?
          AND horario = ?
          AND status = 'confirmada'
        LIMIT 1
    `).get(
        data,
        horario
    );


    if (confirmada) {

        return res.status(409).json({
            erro: "Este horÃ¡rio jÃ¡ foi confirmado."
        });

    }


    /*
     * Verifica reserva temporÃ¡ria
     */

    const temporaria = await db.prepare(`
        SELECT id
        FROM reservas_temporarias
        WHERE data = ?
          AND horario = ?
          AND expira_em > ?
        LIMIT 1
    `).get(
        data,
        horario,
        Date.now()
    );


    if (temporaria) {

        return res.status(409).json({
            erro: "Este horÃ¡rio estÃ¡ temporariamente reservado."
        });

    }


    /*
     * Calcula valores
     */

    const temEscaldaPes = !!escaldaPes;

    const total =
        temEscaldaPes ? 180 : 150;


    /*
     * Reserva por 10 minutos
     */

    const agora = Date.now();

    const expiraEm =
        agora + (10 * 60 * 1000);


    /*
     * GRAVA TODOS OS DADOS
     */

    const resultado = await db.prepare(`
        INSERT INTO reservas_temporarias
        (
            data,
            horario,
            nome,
            cpf,
            whatsapp,
            escalda_pes,
            total,
            expira_em,
            criado_em
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
    `).run(
        data,
        horario,
        nome,
        cpf,
        whatsapp,
        temEscaldaPes ? 1 : 0,
        total,
        expiraEm,
        new Date().toISOString()
    );

const cpfLimpo = limparDocumento(cpf);
const whatsappLimpo = limparDocumento(whatsapp);

const clienteAsaas = await asaasRequest("/customers", {
    method: "POST",
    body: JSON.stringify({
        name: nome,
        cpfCnpj: cpfLimpo,
        mobilePhone: whatsappLimpo,
        externalReference: `OXUMARE-TEMP-${Number(resultado.lastInsertRowid)}`
    })
});

await db.prepare(`
    UPDATE reservas_temporarias
    SET asaas_customer_id = ?
    WHERE id = ?
`).run(
    clienteAsaas.id,
    Number(resultado.lastInsertRowid)
);

const pagamentoAsaas = await asaasRequest("/payments", {
    method: "POST",
    body: JSON.stringify({
        customer: clienteAsaas.id,
        billingType: "PIX",
        value: 50,
        dueDate: dataHojeSaoPaulo(),
        description: `Reserva OxumarÃ© Massagem - ${data} Ã s ${horario}`,
        externalReference: `OXUMARE-TEMP-${Number(resultado.lastInsertRowid)}`
    })
});

await db.prepare(`
    UPDATE reservas_temporarias
    SET asaas_payment_id = ?
    WHERE id = ?
`).run(
    pagamentoAsaas.id,
    Number(resultado.lastInsertRowid)
);

const pixAsaas = await asaasRequest(
    `/payments/${pagamentoAsaas.id}/pixQrCode`
);

await db.prepare(`
    UPDATE reservas_temporarias
    SET
        pix_payload = ?,
        pix_encoded_image = ?,
        pix_expiration = ?
    WHERE id = ?
`).run(
    pixAsaas.payload,
    pixAsaas.encodedImage,
    pixAsaas.expirationDate,
    Number(resultado.lastInsertRowid)
);
    res.json({
    sucesso: true,
    id: Number(resultado.lastInsertRowid),
    data,
    horario,
    nome,
    whatsapp,
    escaldaPes: temEscaldaPes,
    total,
    reserva: 50,
    restante: total - 50,
    expiraEm,
    paymentId: pagamentoAsaas.id,
    pix: {
        payload: pixAsaas.payload,
        encodedImage: pixAsaas.encodedImage,
        expirationDate: pixAsaas.expirationDate
    }
});

});


/*
 * CONFIRMAR RESERVA
 *
 * Futuramente serÃ¡ chamado pelo webhook
 * do Asaas apÃ³s o pagamento.
 */

app.post("/api/confirmar-reserva", async (req, res) => {

    const {
        data,
        horario
    } = req.body;


    if (!data || !horario) {

        return res.status(400).json({
            erro: "Data e horÃ¡rio sÃ£o obrigatÃ³rios."
        });

    }


    /*
     * Procura a reserva temporÃ¡ria
     */

    const temporaria = await db.prepare(`
        SELECT *
        FROM reservas_temporarias
        WHERE data = ?
          AND horario = ?
          AND expira_em > ?
        LIMIT 1
    `).get(
        data,
        horario,
        Date.now()
    );


    if (!temporaria) {

        return res.status(404).json({
            erro: "Reserva temporÃ¡ria nÃ£o encontrada ou expirada."
        });

    }


    /*
     * Verifica se jÃ¡ foi confirmada
     */

    const existente = await db.prepare(`
        SELECT id
        FROM reservas
        WHERE data = ?
          AND horario = ?
          AND status = 'confirmada'
        LIMIT 1
    `).get(
        data,
        horario
    );


    if (existente) {

        return res.status(409).json({
            erro: "Este horÃ¡rio jÃ¡ estÃ¡ confirmado."
        });

    }


    const total =
        Number(temporaria.total);

    const restante =
        total - 50;


    /*
     * Grava a reserva definitiva
     */

    const resultado = await db.prepare(`
        INSERT INTO reservas
        (
            data,
            horario,
            nome,
            whatsapp,
            escalda_pes,
            total,
            reserva,
            restante,
            status,
            criado_em
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    `).run(
        temporaria.data,
        temporaria.horario,
        temporaria.nome,
        temporaria.whatsapp,
        temporaria.escalda_pes,
        total,
        50,
        restante,
        "confirmada",
        new Date().toISOString()
    );


    /*
     * Remove a reserva temporÃ¡ria
     */

    await db.prepare(`
        DELETE FROM reservas_temporarias
        WHERE id = ?
    `).run(
        temporaria.id
    );


    res.json({
        sucesso: true,
        id: Number(resultado.lastInsertRowid),
        mensagem: "Reserva confirmada."
    });

});


/*
 * CONSULTAR RESERVAS CONFIRMADAS
 */

// LOGIN DO ADMINISTRADOR
const sessoesAdmin = new Set();

app.post("/api/admin/login", (req, res) => {
    const { senha } = req.body;

    if (!senha || senha !== process.env.ADMIN_PASSWORD) {
        return res.status(401).json({
            erro: "Senha inválida."
        });
    }

    const token = require("node:crypto").randomUUID();

    sessoesAdmin.add(token);

    res.json({
        sucesso: true,
        token
    });
});

function adminAutenticado(req, res, next) {

    const autorizacao =
        req.headers.authorization || "";

    const token =
        autorizacao.startsWith("Bearer ")
            ? autorizacao.substring(7)
            : "";

    if (!token || !sessoesAdmin.has(token)) {
        return res.status(401).json({
            erro: "Acesso não autorizado."
        });
    }

    next();
}

/*
 * BLOQUEAR HORÁRIO
 */
app.post("/api/admin/bloqueios", adminAutenticado, async (req, res) => {

    const { data, horario } = req.body;

    if (!data || !horario) {
        return res.status(400).json({
            erro: "Data e horário são obrigatórios."
        });
    }

    try {

        await db.prepare(`
            INSERT INTO horarios_bloqueados
            (data, horario, criado_em)
            VALUES (?, ?, ?)
        `).run(
            data,
            horario,
            new Date().toISOString()
        );

        res.json({
            sucesso: true,
            mensagem: "Horário bloqueado com sucesso."
        });

    } catch (erro) {

        if (String(erro.message).includes("UNIQUE")) {
            return res.status(409).json({
                erro: "Este horário já está bloqueado."
            });
        }

        console.error(erro);

        res.status(500).json({
            erro: "Não foi possível bloquear o horário."
        });
    }
});


/*
 * LISTAR HORÁRIOS BLOQUEADOS
 */
app.get("/api/admin/bloqueios", adminAutenticado, async (req, res) => {

    const bloqueios = await db.prepare(`
        SELECT id, data, horario, criado_em
        FROM horarios_bloqueados
        ORDER BY data ASC, horario ASC
    `).all();

    res.json(bloqueios);
});


/*
 * LIBERAR HORÁRIO
 */
app.delete("/api/admin/bloqueios/:id", adminAutenticado, async (req, res) => {

    const id = Number(req.params.id);

    if (!id) {
        return res.status(400).json({
            erro: "ID inválido."
        });
    }

    const resultado = await db.prepare(`
        DELETE FROM horarios_bloqueados
        WHERE id = ?
    `).run(id);

    if (resultado.changes === 0) {
        return res.status(404).json({
            erro: "Bloqueio não encontrado."
        });
    }

    res.json({
        sucesso: true,
        mensagem: "Horário liberado com sucesso."
    });
});

app.get("/api/reservas", adminAutenticado, async (req, res) => {

    const reservas = await db.prepare(`
        SELECT
            id,
            data,
            horario,
            nome,
            whatsapp,
            escalda_pes,
            total,
            reserva,
            restante,
            status,
            criado_em AS criadoEm
        FROM reservas
        ORDER BY data ASC, horario ASC
    `).all();


    res.json(reservas);

});


/*
 * CONSULTAR RESERVAS TEMPORÃRIAS
 *
 * Usaremos isso durante os testes e depois
 * no painel administrativo.
 */

app.get("/api/reservas-temporarias", async (req, res) => {

    await limparReservasTemporarias();

    const reservas = await db.prepare(`
        SELECT
            id,
            data,
            horario,
            nome,
            whatsapp,
            escalda_pes,
            total,
            expira_em AS expiraEm,
            criado_em AS criadoEm
        FROM reservas_temporarias
        ORDER BY data ASC, horario ASC
    `).all();


    res.json(reservas);

});
/*
 * WEBHOOK ASAAS
 * Recebe a confirmaÃ§Ã£o de pagamento
 */



// STATUS DO PAGAMENTO PARA O CLIENTE
app.get("/api/status-pagamento/:paymentId", async (req, res) => {
    try {
        const paymentId = req.params.paymentId;

        const reserva = await db.prepare(`
            SELECT
                id,
                data,
                horario,
                nome,
                whatsapp,
                escalda_pes,
                total,
                asaas_payment_id
            FROM reservas
            WHERE asaas_payment_id = ?
            LIMIT 1
        `).get(paymentId);

        if (reserva) {
            return res.json({
                status: "CONFIRMADO",
                reserva
            });
        }

        const temporaria = await db.prepare(`
            SELECT
                id,
                data,
                horario,
                nome,
                escalda_pes,
                total,
                expira_em,
                asaas_payment_id
            FROM reservas_temporarias
            WHERE asaas_payment_id = ?
            LIMIT 1
        `).get(paymentId);

        if (!temporaria) {
            return res.json({
                status: "NAO_ENCONTRADO"
            });
        }

        if (temporaria.expira_em <= Date.now()) {
            return res.json({
                status: "EXPIRADO"
            });
        }

        return res.json({
            status: "AGUARDANDO_PAGAMENTO",
            reserva: temporaria
        });

    } catch (erro) {
        console.error("Erro ao consultar status do pagamento:", erro);
        return res.status(500).json({
            erro: "Erro ao consultar pagamento"
        });
    }
});

app.post("/api/webhook/asaas", async (req, res) => {

    const tokenRecebido =
        req.headers["asaas-access-token"];

    if (
        !ASAAS_WEBHOOK_TOKEN ||
        tokenRecebido !== ASAAS_WEBHOOK_TOKEN
    ) {
        console.log("Webhook Asaas recusado: token invÃ¡lido.");

        return res
            .status(401)
            .json({ erro: "NÃ£o autorizado" });
    }

    const evento = req.body;

    if (!evento || !evento.id) {
        return res
            .status(400)
            .json({ erro: "Evento invÃ¡lido" });
    }

    try {

        await db.prepare(`
            INSERT INTO asaas_eventos (
                asaas_event_id,
                evento,
                recebido_em
            )
            VALUES (?, ?, ?)
        `).run(
            evento.id,
            evento.event || "DESCONHECIDO",
            new Date().toISOString()
        );

    } catch (erro) {

        if (
            String(erro.message)
            .includes("UNIQUE constraint failed")
        ) {
            console.log(
                "Evento Asaas jÃ¡ processado:",
                evento.id
            );

            return res.json({
                recebido: true,
                duplicado: true
            });
        }

        console.error(
            "Erro ao registrar evento Asaas:",
            erro
        );

        return res
            .status(500)
            .json({ erro: "Erro interno" });
    }

    console.log(
        "Webhook Asaas recebido:",
        evento.event,
        evento.payment?.id || ""
    );

   if (evento.event === "PAYMENT_RECEIVED") {

    const paymentId =
        evento.payment?.id;

    console.log(
        "Pagamento recebido:",
        paymentId
    );

    if (!paymentId) {

        console.log(
            "Webhook sem payment.id."
        );

    } else {

        const reservaTemporaria =
    await db.prepare(`
        SELECT *
        FROM reservas_temporarias
        WHERE asaas_payment_id = ?

        LIMIT 1
    `).get(
        paymentId

    );

        if (!reservaTemporaria) {

            console.log(
                "Nenhuma reserva temporÃ¡ria encontrada para o pagamento:",
                paymentId
            );

        } else {

            const reservaExistente =
                await db.prepare(`
                    SELECT *
                    FROM reservas
                    WHERE data = ?
                    AND horario = ?
                    LIMIT 1
                `).get(
                    reservaTemporaria.data,
                    reservaTemporaria.horario
                );

            if (reservaExistente) {

                console.log(
                    "HorÃ¡rio jÃ¡ possui uma reserva confirmada:",
                    reservaTemporaria.data,
                    reservaTemporaria.horario
                );

            } else {

                await db.prepare(`
                    INSERT INTO reservas (
                        data,
                        horario,
                        nome,
                        cpf,
                        whatsapp,
                        escalda_pes,
                        total,
                        reserva,
                        restante,
                        status,
                        criado_em,
                        asaas_payment_id
                    )
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                `).run(
                    reservaTemporaria.data,
                    reservaTemporaria.horario,
                    reservaTemporaria.nome,
                    reservaTemporaria.cpf,
                    reservaTemporaria.whatsapp,
                    reservaTemporaria.escalda_pes,
                    reservaTemporaria.total,
                    50,
                    reservaTemporaria.total - 50,
                    "confirmada",
                    new Date().toISOString(),
                    paymentId
                );

                await db.prepare(`
                    DELETE FROM reservas_temporarias
                    WHERE id = ?
                `).run(
                    reservaTemporaria.id
                );

                console.log(
                    "RESERVA CONFIRMADA COM SUCESSO:",
                    reservaTemporaria.data,
                    reservaTemporaria.horario
                );
            }
        }
    }
}

    return res.json({
        recebido: true
    });
});

/*
 * INICIAR SERVIDOR
 */

async function iniciarServidor() {
    try {
        await inicializarBanco();

        const servidor = app.listen(PORT, () => {
            console.log(
                `OxumarÃ© Massagem rodando em http://localhost:${PORT}`
            );
            console.log(
                "Banco de dados: PostgreSQL (Supabase)"
            );
        });

        servidor.on("error", (erro) => {
            console.error("ERRO NO SERVIDOR:", erro);
        });
    } catch (erro) {
        console.error("ERRO AO INICIALIZAR O BANCO:", erro);
        process.exit(1);
    }
}

iniciarServidor();
